### PR TITLE
Feature/819 upgrade python v3.10

### LINKED ISSUE #819: Upgrade python to 3.10.X
Here's the breakdown for python current versions. We are getting security fixes, but no bug fixes until 2025. We should upgrade all our repos when we have time. 
https://devguide.python.org/versions/

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] https://github.com/fecgov/openFEC/issues/5682

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] Upgrade python to 3.10.X

### PR DESCRIPTION
**Pull request by tmpayton**
## Summary (required)

- Resolves #819 

This ticket upgrades python to version 3.10.13. 

## Impacted areas of the application

General components of the application that this PR will affect:

-  circleci pipeline
- parsing

## How to test
1. Checkout this branch 

**Terminal One:** 
2. `pyenv install 3.10.13`
3. `pyenv virtualenv 3.10.13 <new virtual environment>`
4. `pyenv activate <new virtual environment>`
5. `pip install -r requirements.txt`
6. `rm -rf node_modules`
7. `npm i`
8. `npm run build`
9. `dropdb eregs_local`
10. `createdb eregs_local`
11. `python manage.py migrate`
12. `python manage.py compile_frontend`
13. `python manage.py runserver` (leave running)

**Terminal Two:**
14. `pyenv virtualenv 3.10.13 <new parsing environment>`
15. `pyenv activate <new parsing environment>`
16. `pip install -r requirements-parsing.txt`
17. `python load_regs/load_fec_regs.py local`
18. Go to http://127.0.0.1:8000/  to view 45 regulations 

For more detailed instructions [follow the wiki](https://github.com/fecgov/fec-eregs/wiki/Parse-regulations-on-local) on how to setup/parse regulations on local environment

### CODE REVIEW

**Review by pkfec — COMMENTED** [review]
> ## How to test

> **Terminal One:** 2. `pyenv virtualenv 3.10.13 <new virtual environment>` 3. `pyenv activate <new virtual environment>` 
> 

@tmpayton Could you include the following step to install pyenv version 3.10.13 before testing your pull request?
- pyenv install 3.10.13

**Comment by tmpayton** [comment]
> > ## How to test
> 
> > **Terminal One:** 2. `pyenv virtualenv 3.10.13 <new virtual environment>` 3. `pyenv activate <new virtual environment>`
> 
> @tmpayton Could you include the following step to install pyenv version 3.10.13 before testing your pull request?
> 
> * pyenv install 3.10.13

done! @pkfec

**Comment by pkfec** [comment]
> > > ## How to test
> > 
> > 
> > > **Terminal One:** 2. `pyenv virtualenv 3.10.13 <new virtual environment>` 3. `pyenv activate <new virtual environment>`
> > 
> > 
> > @tmpayton Could you include the following step to install pyenv version 3.10.13 before testing your pull request?
> > 
> > * pyenv install 3.10.13
> 
> done! @pkfec

Thanks @tmpayton

**Review by pkfec — APPROVED** [review]
Parser works as expected. Thanks @tmpayton

**Pull request merged**
