### PR TITLE
update packages to get local eregs parser working as backup

### PR DESCRIPTION
**Pull request by jason-upchurch**
### Summary
a possible backup for parsing eregs locally, based off 4/14/2020 deploy.
also upgraded webargs to 5.5.3 to resolve snyk security vulnerability (replacing https://github.com/fecgov/fec-eregs/pull/482)

### How to test
- [ ] pip install new requirements.txt in a 3.7.5 clean environment
- [ ] try going through setup steps to include local parsing
- [ ] please contact @jason-upchurch with for additional pairing and any questions!

### CODE REVIEW

**Comment by pkfec** [comment]
Tried setting up and parsing the regs on local env. Only 7 regs parsed and rest of them failed with errors shown below. I noticed these parsing error happened on my local environment in 2018 which i logged an issue here #426. 

@jason-upchurch is able to parse all 2019 regs on his local env. Nicely done.
I would suggest some other team member test this PR before merging this change.
cc @fec-jli @lbeaufort 

(jasonenv) macadmins-MacBook-Pro-5:fec-eregs pkasireddy$ **python load_regs/load_fec_regs.py** local
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, index, jobs, sessions
Running migrations:
  No migrations to apply.
2020-04-22 19:12:57 regparser.commands.annual_version        No annual edition for 11 CFR 1, Year: 2020. Trying 2019.
2020-04-22 19:12:57 regparser.history.annual                 No <PARTS> in https://www.gpo.gov/fdsys/bulkdata/CFR/2019/title-11/CFR-2019-title11-vol1.xml. Assuming this volume contains all of the regs
2020-04-22 19:12:57 regparser.commands.annual_version        Getting annual version - 11 CFR 1, Year: 2019
2020-04-22 19:12:58 regparser.tree.gpo_cfr.builder           Build tree <Element CFRGRANULE at 0x10b883460>
2020-04-22 19:12:58 regparser.tree.gpo_cfr.builder           Preprocessing XML <Element CFRGRANULE at 0x10b883460>
2020-04-22 19:12:58 regparser.content                        Could not load macros from regcontent.macros
Traceback (most recent call last):
  File “/Users/pkasireddy/.pyenv/versions/jasonenv/bin/eregs”, line 10, in <module>
    sys.exit(eregs())
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/web/management/runner.py”, line 22, in eregs
    runner(args)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/web/management/runner.py”, line 14, in runner
    execute_from_command_line(argv)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/django/core/management/_init_.py”, line 364, in execute_from_command_line
    utility.execute()
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/django/core/management/_init_.py”, line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/djclick/adapter.py”, line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 717, in main
    rv = self.invoke(ctx)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/djclick/adapter.py”, line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/retry.py”, line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/retry.py”, line 57, in run_or_resolve
    cmd()
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/retry.py”, line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 555, in invoke
    return callback(*args, **kwargs)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/decorators.py”, line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/pipeline.py”, line 32, in pipeline
    ctx.invoke(annual_version, **params)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 555, in invoke
    return callback(*args, **kwargs)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/annual_version.py”, line 73, in annual_version
    process_if_needed(vol, cfr_part)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/annual_version.py”, line 29, in process_if_needed
    tree = builder.build_tree(annual_entry.read().xml)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/builder.py”, line 98, in build_tree
    plugin(tree, xml_node)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 258, in _call_
    sections = build_from_section(parent.cfr_part, xml_node)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 159, in build_from_section
    RegtextParagraphProcessor().process(section_xml, sect_node)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/xml_parser/paragraph_processor.py”, line 122, in process
    nodes = self.parse_nodes(xml)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/xml_parser/paragraph_processor.py”, line 48, in parse_nodes
    nodes.extend(tag_matcher.derive_nodes(child, processor=self))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 208, in derive_nodes
    for marker, plain_text, tagged_text in split_by_markers(xml):
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 188, in split_by_markers
    markers_list = get_markers(tagged_text, next_marker(xml))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 52, in get_markers
    collapsed = collapsed_markers(text)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 101, in collapsed_markers
    potential = [trip for trip in remove_citation_overlaps(text, potential)]
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 302, in remove_citation_overlaps
    return [(m, start, end) for m, start, end in possible_markers
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 306, in <listcomp>
    for e in internal_citations(text))]
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 250, in internal_citations
    multiple(grammar.multiple_non_comments, False)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 246, in multiple
    initial_label, comment))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 223, in multiple_citations
    match.pos.start, match.pos.end, new_label,
**AttributeError: ‘str’ object has no attribute ‘start’**

**Comment by fec-jli** [comment]
Thanks you work on this.
1)test on local, create brand new virtue env.
pip install -r requirements.txt is fine. 
eregs app works well (point to prod eregs api)

2)could not parse eregs locally. error:
Screen Shot 2020-04-28 at 9 11 54 PM

3)another small issue
when run: pip install -r requirements_dev.txt
got error:
Screen Shot 2020-04-28 at 9 15 00 PM

**Comment by jason-upchurch** [comment]
> Thank you work on this.
> 1)test on local, create brand new virtue env.
> pip install -r requirements.txt is fine.
> eregs app works well (point to prod eregs api)
> 
> 2)could not parse eregs locally. error:
> Screen Shot 2020-04-28 at 9 11 54 PM
> 
> 3)another small issue
> when run: pip install -r requirements_dev.txt
> got error:
> Screen Shot 2020-04-28 at 9 15 00 PM

Thank you @fec-jli ! I'll take a look at that error today.

**Comment by fec-jli** [comment]
Traceback (most recent call last):
  File "/Users/jli/.pyenv/versions/pyenv375/bin/eregs", line 10, in <module>
    sys.exit(eregs())
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/web/management/runner.py", line 22, in eregs
    runner(args)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/web/management/runner.py", line 14, in runner
    execute_from_command_line(argv)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/djclick/adapter.py", line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/djclick/adapter.py", line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/retry.py", line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/retry.py", line 68, in run_or_resolve
    run_or_resolve(cmd, e.dependency)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/retry.py", line 57, in run_or_resolve
    cmd()
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/retry.py", line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/pipeline.py", line 32, in pipeline
    ctx.invoke(annual_version, **params)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/annual_version.py", line 73, in annual_version
    process_if_needed(vol, cfr_part)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/commands/annual_version.py", line 29, in process_if_needed
    tree = builder.build_tree(annual_entry.read().xml)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/builder.py", line 98, in build_tree
    plugin(tree, xml_node)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py", line 258, in __call__
    sections = build_from_section(parent.cfr_part, xml_node)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py", line 159, in build_from_section
    RegtextParagraphProcessor().process(section_xml, sect_node)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/xml_parser/paragraph_processor.py", line 122, in process
    nodes = self.parse_nodes(xml)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/xml_parser/paragraph_processor.py", line 48, in parse_nodes
    nodes.extend(tag_matcher.derive_nodes(child, processor=self))
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py", line 208, in derive_nodes
    for marker, plain_text, tagged_text in split_by_markers(xml):
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py", line 188, in split_by_markers
    markers_list = get_markers(tagged_text, next_marker(xml))
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py", line 52, in get_markers
    collapsed = collapsed_markers(text)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py", line 101, in collapsed_markers
    potential = [trip for trip in remove_citation_overlaps(text, potential)]
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/citations.py", line 302, in remove_citation_overlaps
    return [(m, start, end) for m, start, end in possible_markers
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/citations.py", line 306, in <listcomp>
    for e in internal_citations(text))]
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/citations.py", line 258, in internal_citations
    single(grammar.marker_paragraph, False)
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/citations.py", line 242, in single
    initial_label, comment))
  File "/Users/jli/.pyenv/versions/3.7.5/envs/pyenv375/lib/python3.7/site-packages/regparser/citations.py", line 201, in single_citations
    start = match.marker.pos[1]
IndexError: string index out of range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Pull request closed without merging**
