### PR TITLE
add reqs for parsing

### PR DESCRIPTION
**Pull request by jason-upchurch**
### Summary
loading regulations requires different python libraries. This PR adds a sufficient set up packages for local parsing. Later, this list can be trimmed down to represent only the necessary libraries.

### How to test
- [x] review https://fec-dev-eregs.app.cloud.gov/regulations/ (@dorothyyeager if others should review, please let me know!)
- [x] using Python 3.6.1 attempt to parse regs locally with the `requirements-parsing.txt` file installed (@fec-jli @pkfec )

### CODE REVIEW

**Comment by jason-upchurch** [comment]
> Reviewed on dev and overall it looked good. I did catch some things that need tweaking:
> 
> 11 CFR 100.19 - in the heading, boldface "file, filed and filing"
> 
> 11 CFR 100.19(a) - We aren't linking to section 1.2 of the rules. (This is the thing addressed by #393)
> 
> 11 CFR 102.1 - We need to update the heading to add a cite so it reads "Registration of politicalcommittees (52 U.S.C. 30102(g), 30103(a))."
> 
> 11 CFR 102.2 - Add space after first sentence (after "Form 1")
> 
> 11 CFR 102.3 - Sometimes we're linking externally to govinfo and sometimes internally to e-regs. I think the internal link is more user-friendly, but most important, we should be consistent throughout. I may not have caught every instance.
> 
> 11 CFR 104.3(b)(3)(vii)(C) and (D) - former section (C) was moved to (D) and changed. A new paragraph was added at (C).
> 
> Insert this as 104.3(b)(3)(vii)(C):
> (C) For an independent expenditure that is made in support of or opposition to a presidential primary candidate and is publicly distributed or otherwise publicly disseminated in six or more states but does not refer to any particular state, the political committee must report the independent expenditure as a single expenditure—i.e., without allocating it among states—and must indicate the state with the
> next upcoming presidential primary among those states where the independent expenditure is distributed, as specified in § 104.4(f)(2). The political committee must use memo text to indicate the states in which the communication is distributed.
> 
> Insert this as 104.3(b)(3)(vii)(D):
> (D) The information required by paragraphs (b)(3)(vii)(A) through (C) of this section shall be reported on Schedule E as part of a report covering the reporting period in which the aggregate disbursements for any independent expenditure to any person exceed $200 per calendar year. Schedule E shall also include the total of all such expenditures of $200 or less made during the reporting period.
> 
> 11 CFR 104.3(e)(5) - missing link to section 1.2 of the rules.
> 
> 11 CFR 104.4 - Sometimes we're linking externally to govinfo and sometimes internally to e-regs.
> 
> 11 CFR 104.4(f) - missing link to 11 CFR 109.10(d).
> 
> 11 CFR 104.20 - Sometimes we're linking externally to govinfo and sometimes internally to e-regs.
> 
> 11 CFR 105.1 - missing link to section 1.2 of the rules.
> 
> 11 CFR 105.2 - 105.5 - Is there a way to make it read "105.2-105.5" (instead of 2-5)?
> 
> 11 CFR 110.6 - Sometimes we're linking externally to govinfo and sometimes internally to e-regs.

@dorothyyeager It looks like that icebox issue you posted in slack yesterday deals with the linking problems that appear to be standard "bugs" (https://github.com/fecgov/fec-eregs/issues/393)

Would you be okay with us deferring the "link" comments from your review above to the iceboxed issue instead? My thinking is that if there is a _reason_ regs parse with some links not working consistently, we could address it strategically so that we don't overlook a more strategic solution in favor of repeating the link activity every year. What do you think?
cc @patphongs @PaulClark2 @AmyKort

**Comment by jason-upchurch** [comment]
> 11 CFR 100.19 - in the heading, boldface "file, filed and filing"
@dorothyyeager this does not appear to be bolded in 2019 on our live website either. Stylistically, I'd say this issue might be best addressed under a more comprehensive "tweak eregs xml for correct parsing" because if the problem existed in the previous years, without dealing with it strategically,  we'll be doing these tweaks every year. Would you be okay with my moving comments that generally persisted in past years to a new issue so that the publication is not held up by previously-accepted formatting issues? cc @patphongs @PaulClark2 @AmyKort

**Comment by dorothyyeager** [comment]
@jason-upchurch I'm fine with deferring those link fixes; what you've proposed makes sense to me. Another icebox issue: https://github.com/fecgov/fec-eregs/issues/446 relates to this as well.

**Comment by dorothyyeager** [comment]
Checked on stage and it looks good. All the needed changes from a content/legal perspective have been made. Thanks @jason-upchurch

**Comment by pkfec** [comment]
I was finally able to parsed 2020 regs on my local env.  Thanks @jason-upchurch for identifying the right packages to parse regs.

**Comment by pkfec** [comment]
@jason-upchurch i think the parser only work with python v3.6.1 and its not mentioned anywhere in the requirements.

**Comment by dorothyyeager** [comment]
Just wanted to thank @jason-upchurch @fec-jli and @pkfec for their hard work on e-regs - as a former Information Division person, I can say first hand that it's a feature that FEC staff and the people we regulate really use so it's great to have it updated for 2020.

**Pull request merged**
