### PR TITLE
upgrade celery and related packages

### LINKED ISSUE #655: [Snyk: High]: Celery Stored Command Injection(due 02/24/2022)
### Overview
Affected versions of this package are vulnerable to Stored Command Injection. It by default trusts the messages and metadata stored in backends (result stores). When reading task metadata from the backend, the data is deserialized. Given that an attacker can gain access to, or somehow manipulate the metadata within a celery backend, they could trigger a stored command injection vulnerability and potentially gain further access to the system.

https://security.snyk.io/vuln/SNYK-PYTHON-CELERY-2314953

### Detailed path:
Introduced through: project@0.0.0 › celery@4.1.0

### Completion criteria:
- [ ]  Upgrade celery to version 5.2.2
- [ ]  parser functionality works

### PR DESCRIPTION
**Pull request by pkfec**
## Summary (required)

Upgrade celery package to the latest and parser compatible version.

- Resolves #655 

(Include a summary of proposed changes and connect issue below)

- upgrade celery to version 5.2.3 in requirements.txt and requirements-parsing.txt

### Required reviewers

Two developers must

## How to test

Terminal 1 (for eregs): 
-  git checkout feature/upgrade-celery
- pyenv virtualenv venv-eregs
- pyenv activate venv-eregs
- pip install -r requirements.txt
- rm -rf node_modules
- npm i
- npm run build
- dropdb eregs-db
- createdb eregs-db
- python manage.py migrate
- npm install -g grunt-cli (In case you run into **No such file or directory: 'grunt': 'grunt'** error)
- python manage.py compile_frontend
- python manage.py runserver
- copy and paste URL in a browser : http://localhost:8000/ 

Terminal 2 (for parser):
- pyenv virtualenv venv-parser
- pyenv activate venv-parser
- pip install -r requirements-parsing.txt
- python load_regs/load_fec_regs.py local (2021 regulations will be parsed locally and uploaded to local API)

All 45 regulations should appear on the browser:http://localhost:8000/

**Screenshots:**
Screen Shot 2022-02-01 at 7 55 20 PM

Screen Shot 2022-02-01 at 7 56 26 PM

### CODE REVIEW

**Comment by pkfec** [comment]
@fec-jli @johnnyporkchops @hcaofec @patphongs There are few issues with the parser that i need to fix. Changed the status of this PR to WIP.  I will send an update when the PR is ready for your review

**Comment by pkfec** [comment]
Bumping celery in `requirements.txt` file caused some package incompatible inside `requirements-parsing.txt`
I fixed all the package incompatible errors encountered while installing requirements-parser.txt. 

Thanks @johnnyporkchops for flagging the errors.

```
ERROR: click-didyoumean 0.3.0 has requirement click>=7, but you'll have click 6.7 which is incompatible.

ERROR: celery 5.2.3 has requirement billiard<4.0,>=3.6.4.0, but you'll have billiard 3.5.0.3 which is incompatible.

ERROR: celery 5.2.3 has requirement click<9.0,>=8.0.3, but you'll have click 6.7 which is incompatible.

ERROR: celery 5.2.3 has requirement kombu<6.0,>=5.2.3, but you'll have kombu 4.1.0 which is incompatible.

ERROR: celery 5.2.3 has requirement pytz>=2021.3, but you'll have pytz 2018.3 which is incompatible.

ERROR: celery 5.2.3 has requirement vine<6.0,>=5.0.0, but you'll have vine 1.1.4 which is incompatible.
```

@johnnyporkchops @fec-jli @johnnyporkchops @patphongs This PR is now ready for your review.

**Review by johnnyporkchops — APPROVED** [review]
Tested end to end, parsing works locally. Great work!

**Review by fec-jli — APPROVED** [review]
test locally, work as expected. Thanks

**Pull request merged**
